[project]
name = "ambikha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygments>=2.19.1",
    "pytest>=8.3.4",
    "pytest-bdd>=8.1.0",
    "pytest-cov>=6.0.0",
]
